apiVersion: apps/v1
kind: Deployment

metadata:
  name: docuhelper-file-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: docuhelper-file
  template:
    metadata:
      labels:
        app: docuhelper-file
    spec:
      containers:
        - name: docuhelper-file-container
          image: docker.bmserver.org/docuhelper-file:$IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: docuhelper-configmap-prod
---

apiVersion: v1
kind: Service

metadata:
  name: docuhelper-file-service

spec:
  type: ClusterIP
  clusterIP: 10.98.59.138
  selector:
    app: docuhelper-file
  ports:
    - protocol: TCP
      targetPort: 8082    # pod 포트
      port: 8082          # 서비스 내부 포트