apiVersion: apps/v1
kind: Deployment

metadata:
  name: docuhelper-file-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: docuhelper-file
  template:
    metadata:
      labels:
        app: docuhelper-file
    spec:
      containers:
        - name: docuhelper-file-container
          image: docker.bmserver.org/docuhelper-file
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: docuhelper-configmap-prod
---

apiVersion: v1
kind: Service

metadata:
  name: docuhelper-file-service

spec:
  type: NodePort
  selector:
    app: docuhelper-file
  ports:
    - protocol: TCP
      targetPort: 8080    # pod 포트
      port: 8080          # 서비스 내부 포트
      nodePort: 30001      # 서비스 외부 포트
