server:
  port: ${PORT:8082}

spring:
  application:
    name: docuhelper-file
  r2dbc:
    url: r2dbc:pool:postgres://${DB_HOST}:${DB_PORT}/docuhelper
    username: ${DB_USER}
    password: ${DB_PASSWD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    consumer:
      auto-offset-reset: earliest

s3:
  bucket: ${S3_BUCKET}
  endPoint: ${S3_ENDPOINT}
  region: ${S3_REGION}
  credentials:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}

