server:
  port: ${PORT:8082}

spring:
  application:
    name: docuhelper-file
  r2dbc:
    url: r2dbc:pool:postgres://${DB_HOST:192.168.0.7}:${DB_PORT:5432}/${DB_SCHEMA:docuhelper} # schema ??? webflux? ???
    username: ${DB_USER:postgres}
    password: ${DB_PASSWD:password}

s3:
  bucket: ${S3_BUCKET:docuhelper}
  endPoint: ${S3_ENDPOINT:http://192.168.0.7:9000}
  region: ${S3_REGION:ap-northeast-2}
  credentials:
    accessKey: ${S3_ACCESS_KEY:minioadmin}
    secretKey: ${S3_SECRET_KEY:minioadmin}

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

